// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8fpPLnZvjSd7hMThinyq1b7i_JgjNPzg',
    appId: '1:461523142592:web:1542af89703c1eb9dd2a25',
    messagingSenderId: '461523142592',
    projectId: 'deskive-dc51e',
    authDomain: 'deskive-dc51e.firebaseapp.com',
    storageBucket: 'deskive-dc51e.firebasestorage.app',
    measurementId: 'G-2CMSL4JTL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLayLLtuC6EyU6-3t7Fw736C2yVSYMdjg',
    appId: '1:937537821812:android:3f4803c93fb4be64134521',
    messagingSenderId: '937537821812',
    projectId: 'deskive-app',
    storageBucket: 'deskive-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7GcvE8uew7iofMsNM6nZHSfpl9nYIOcw',
    appId: '1:937537821812:ios:9add34c638313434134521',
    messagingSenderId: '937537821812',
    projectId: 'deskive-app',
    storageBucket: 'deskive-app.firebasestorage.app',
    iosBundleId: 'com.deskive.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7GcvE8uew7iofMsNM6nZHSfpl9nYIOcw',
    appId: '1:937537821812:ios:9add34c638313434134521',
    messagingSenderId: '937537821812',
    projectId: 'deskive-app',
    storageBucket: 'deskive-app.firebasestorage.app',
    iosBundleId: 'com.deskive.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8fpPLnZvjSd7hMThinyq1b7i_JgjNPzg',
    appId: '1:461523142592:web:a88c567148beb9b2dd2a25',
    messagingSenderId: '461523142592',
    projectId: 'deskive-dc51e',
    authDomain: 'deskive-dc51e.firebaseapp.com',
    storageBucket: 'deskive-dc51e.firebasestorage.app',
    measurementId: 'G-RFWFKPVEJ1',
  );
}
