import 'package:flutter/foundation.dart';
import '../models/notification.dart';
import '../config/app_config.dart';
import 'notification_service.dart';

class NotificationIntegrationService {
  static NotificationIntegrationService? _instance;
  static NotificationIntegrationService get instance => _instance ??= NotificationIntegrationService._();
  
  NotificationIntegrationService._();

  final NotificationService _notificationService = NotificationService.instance;

  // Task notifications
  Future<void> sendTaskNotification({
    required String taskId,
    required String taskTitle,
    required String recipientUserId,
    required String senderName,
    String? senderAvatar,
    required TaskNotificationType type,
    String? projectId,
    String? projectName,
    String? workspaceId,
    Map<String, dynamic>? additionalData,
  }) async {
    try {
      String title = '';
      String body = '';
      NotificationPriority priority = NotificationPriority.medium;
      List<NotificationAction> actions = [];

      switch (type) {
        case TaskNotificationType.assigned:
          title = 'New Task Assigned';
          body = '$senderName assigned you a task: "$taskTitle"';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'view_task',
              type: NotificationActionType.openItem,
              label: 'View Task',
              data: {'task_id': taskId, 'project_id': projectId},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'mark_complete',
              type: NotificationActionType.custom,
              label: 'Mark Complete',
              data: {'task_id': taskId, 'action': 'complete'},
            ),
          ];
          break;
        case TaskNotificationType.completed:
          title = 'Task Completed';
          body = '$senderName completed the task: "$taskTitle"';
          actions = [
            NotificationAction(
              id: 'view_task',
              type: NotificationActionType.openItem,
              label: 'View Task',
              data: {'task_id': taskId, 'project_id': projectId},
              isPrimary: true,
            ),
          ];
          break;
        case TaskNotificationType.dueSoon:
          title = 'Task Due Soon';
          body = 'Task "$taskTitle" is due soon';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'view_task',
              type: NotificationActionType.openItem,
              label: 'View Task',
              data: {'task_id': taskId, 'project_id': projectId},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'snooze',
              type: NotificationActionType.custom,
              label: 'Snooze',
              data: {'task_id': taskId, 'action': 'snooze'},
            ),
          ];
          break;
        case TaskNotificationType.overdue:
          title = 'Task Overdue';
          body = 'Task "$taskTitle" is overdue';
          priority = NotificationPriority.highest;
          actions = [
            NotificationAction(
              id: 'view_task',
              type: NotificationActionType.openItem,
              label: 'View Task',
              data: {'task_id': taskId, 'project_id': projectId},
              isPrimary: true,
            ),
          ];
          break;
        case TaskNotificationType.updated:
          title = 'Task Updated';
          body = '$senderName updated the task: "$taskTitle"';
          actions = [
            NotificationAction(
              id: 'view_task',
              type: NotificationActionType.openItem,
              label: 'View Changes',
              data: {'task_id': taskId, 'project_id': projectId},
              isPrimary: true,
            ),
          ];
          break;
        case TaskNotificationType.commented:
          title = 'New Comment';
          body = '$senderName commented on task: "$taskTitle"';
          actions = [
            NotificationAction(
              id: 'view_task',
              type: NotificationActionType.openItem,
              label: 'View Comment',
              data: {'task_id': taskId, 'project_id': projectId},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'reply',
              type: NotificationActionType.respond,
              label: 'Reply',
              data: {'task_id': taskId, 'action': 'reply'},
            ),
          ];
          break;
      }

      final notification = NotificationModel(
        id: '', // Will be generated by API
        title: title,
        body: body,
        category: NotificationCategory.task,
        priority: priority,
        actions: actions,
        metadata: NotificationMetadata(
          entityId: taskId,
          entityType: 'task',
          workspaceId: workspaceId ?? await AppConfig.getCurrentWorkspaceId(),
          projectId: projectId,
          additionalData: additionalData,
        ),
        createdAt: DateTime.now(),
        senderId: await AppConfig.getCurrentUserId(),
        senderName: senderName,
        senderAvatar: senderAvatar,
      );

      // TODO: Re-implement when backend notification API is ready
      // await _notificationService.apiService.createNotification(notification);
    } catch (e) {
    }
  }

  // Project notifications
  Future<void> sendProjectNotification({
    required String projectId,
    required String projectName,
    required String recipientUserId,
    required String senderName,
    String? senderAvatar,
    required ProjectNotificationType type,
    String? workspaceId,
    Map<String, dynamic>? additionalData,
  }) async {
    try {
      String title = '';
      String body = '';
      NotificationPriority priority = NotificationPriority.medium;
      List<NotificationAction> actions = [];

      switch (type) {
        case ProjectNotificationType.invited:
          title = 'Project Invitation';
          body = '$senderName invited you to join the project "$projectName"';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'accept',
              type: NotificationActionType.approve,
              label: 'Accept',
              data: {'project_id': projectId, 'action': 'accept'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'decline',
              type: NotificationActionType.reject,
              label: 'Decline',
              data: {'project_id': projectId, 'action': 'decline'},
            ),
          ];
          break;
        case ProjectNotificationType.updated:
          title = 'Project Updated';
          body = '$senderName updated the project "$projectName"';
          actions = [
            NotificationAction(
              id: 'view_project',
              type: NotificationActionType.openItem,
              label: 'View Project',
              data: {'project_id': projectId},
              isPrimary: true,
            ),
          ];
          break;
        case ProjectNotificationType.completed:
          title = 'Project Completed';
          body = 'Project "$projectName" has been completed';
          actions = [
            NotificationAction(
              id: 'view_project',
              type: NotificationActionType.openItem,
              label: 'View Project',
              data: {'project_id': projectId},
              isPrimary: true,
            ),
          ];
          break;
        case ProjectNotificationType.deadline:
          title = 'Project Deadline';
          body = 'Project "$projectName" deadline is approaching';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'view_project',
              type: NotificationActionType.openItem,
              label: 'View Project',
              data: {'project_id': projectId},
              isPrimary: true,
            ),
          ];
          break;
      }

      final notification = NotificationModel(
        id: '', // Will be generated by API
        title: title,
        body: body,
        category: NotificationCategory.project,
        priority: priority,
        actions: actions,
        metadata: NotificationMetadata(
          entityId: projectId,
          entityType: 'project',
          workspaceId: workspaceId ?? await AppConfig.getCurrentWorkspaceId(),
          additionalData: additionalData,
        ),
        createdAt: DateTime.now(),
        senderId: await AppConfig.getCurrentUserId(),
        senderName: senderName,
        senderAvatar: senderAvatar,
      );

      // TODO: Re-implement when backend notification API is ready
      // await _notificationService.apiService.createNotification(notification);
    } catch (e) {
    }
  }

  // Calendar notifications
  Future<void> sendCalendarNotification({
    required String eventId,
    required String eventTitle,
    required String recipientUserId,
    required String senderName,
    String? senderAvatar,
    required CalendarNotificationType type,
    DateTime? eventDateTime,
    String? workspaceId,
    Map<String, dynamic>? additionalData,
  }) async {
    try {
      String title = '';
      String body = '';
      NotificationPriority priority = NotificationPriority.medium;
      List<NotificationAction> actions = [];

      switch (type) {
        case CalendarNotificationType.invited:
          title = 'Meeting Invitation';
          body = '$senderName invited you to "$eventTitle"';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'accept',
              type: NotificationActionType.approve,
              label: 'Accept',
              data: {'event_id': eventId, 'action': 'accept'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'decline',
              type: NotificationActionType.reject,
              label: 'Decline',
              data: {'event_id': eventId, 'action': 'decline'},
            ),
          ];
          break;
        case CalendarNotificationType.reminder:
          title = 'Meeting Reminder';
          body = 'Meeting "$eventTitle" starts in 15 minutes';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'join',
              type: NotificationActionType.openItem,
              label: 'Join',
              data: {'event_id': eventId, 'action': 'join'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'snooze',
              type: NotificationActionType.custom,
              label: 'Snooze',
              data: {'event_id': eventId, 'action': 'snooze'},
            ),
          ];
          break;
        case CalendarNotificationType.updated:
          title = 'Meeting Updated';
          body = '$senderName updated the meeting "$eventTitle"';
          actions = [
            NotificationAction(
              id: 'view_event',
              type: NotificationActionType.openItem,
              label: 'View Changes',
              data: {'event_id': eventId},
              isPrimary: true,
            ),
          ];
          break;
        case CalendarNotificationType.cancelled:
          title = 'Meeting Cancelled';
          body = '$senderName cancelled the meeting "$eventTitle"';
          actions = [
            NotificationAction(
              id: 'view_event',
              type: NotificationActionType.openItem,
              label: 'View Event',
              data: {'event_id': eventId},
              isPrimary: true,
            ),
          ];
          break;
      }

      final notification = NotificationModel(
        id: '', // Will be generated by API
        title: title,
        body: body,
        category: NotificationCategory.calendar,
        priority: priority,
        actions: actions,
        metadata: NotificationMetadata(
          entityId: eventId,
          entityType: 'calendar_event',
          workspaceId: workspaceId ?? await AppConfig.getCurrentWorkspaceId(),
          additionalData: additionalData,
        ),
        createdAt: DateTime.now(),
        senderId: await AppConfig.getCurrentUserId(),
        senderName: senderName,
        senderAvatar: senderAvatar,
      );

      // TODO: Re-implement when backend notification API is ready
      // await _notificationService.apiService.createNotification(notification);
    } catch (e) {
    }
  }

  // Chat notifications
  Future<void> sendChatNotification({
    required String channelId,
    required String channelName,
    required String messageId,
    required String messagePreview,
    required String recipientUserId,
    required String senderName,
    String? senderAvatar,
    required ChatNotificationType type,
    String? workspaceId,
    bool isDirectMessage = false,
    Map<String, dynamic>? additionalData,
  }) async {
    try {
      String title = '';
      String body = '';
      NotificationPriority priority = NotificationPriority.medium;
      List<NotificationAction> actions = [];

      switch (type) {
        case ChatNotificationType.message:
          if (isDirectMessage) {
            title = 'Direct Message';
            body = '$senderName: $messagePreview';
            priority = NotificationPriority.high;
          } else {
            title = 'New Message in #$channelName';
            body = '$senderName: $messagePreview';
          }
          actions = [
            NotificationAction(
              id: 'reply',
              type: NotificationActionType.respond,
              label: 'Reply',
              data: {'channel_id': channelId, 'message_id': messageId, 'action': 'reply'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'view_channel',
              type: NotificationActionType.openItem,
              label: 'View Channel',
              data: {'channel_id': channelId},
            ),
          ];
          break;
        case ChatNotificationType.mention:
          title = 'You were mentioned';
          body = '$senderName mentioned you in #$channelName: $messagePreview';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'reply',
              type: NotificationActionType.respond,
              label: 'Reply',
              data: {'channel_id': channelId, 'message_id': messageId, 'action': 'reply'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'view_message',
              type: NotificationActionType.openItem,
              label: 'View Message',
              data: {'channel_id': channelId, 'message_id': messageId},
            ),
          ];
          break;
        case ChatNotificationType.channelInvite:
          title = 'Channel Invitation';
          body = '$senderName invited you to join #$channelName';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'accept',
              type: NotificationActionType.approve,
              label: 'Join Channel',
              data: {'channel_id': channelId, 'action': 'join'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'decline',
              type: NotificationActionType.reject,
              label: 'Decline',
              data: {'channel_id': channelId, 'action': 'decline'},
            ),
          ];
          break;
      }

      final notification = NotificationModel(
        id: '', // Will be generated by API
        title: title,
        body: body,
        category: NotificationCategory.chat,
        priority: priority,
        actions: actions,
        metadata: NotificationMetadata(
          entityId: channelId,
          entityType: 'channel',
          workspaceId: workspaceId ?? await AppConfig.getCurrentWorkspaceId(),
          channelId: channelId,
          additionalData: {
            'message_id': messageId,
            'is_direct_message': isDirectMessage,
            ...?additionalData,
          },
        ),
        createdAt: DateTime.now(),
        senderId: await AppConfig.getCurrentUserId(),
        senderName: senderName,
        senderAvatar: senderAvatar,
      );

      // TODO: Re-implement when backend notification API is ready
      // await _notificationService.apiService.createNotification(notification);
    } catch (e) {
    }
  }

  // File sharing notifications
  Future<void> sendFileNotification({
    required String fileId,
    required String fileName,
    required String recipientUserId,
    required String senderName,
    String? senderAvatar,
    required FileNotificationType type,
    String? projectId,
    String? workspaceId,
    Map<String, dynamic>? additionalData,
  }) async {
    try {
      String title = '';
      String body = '';
      NotificationPriority priority = NotificationPriority.medium;
      List<NotificationAction> actions = [];

      switch (type) {
        case FileNotificationType.shared:
          title = 'File Shared';
          body = '$senderName shared a file with you: "$fileName"';
          actions = [
            NotificationAction(
              id: 'download',
              type: NotificationActionType.custom,
              label: 'Download',
              data: {'file_id': fileId, 'action': 'download'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'view',
              type: NotificationActionType.openItem,
              label: 'View',
              data: {'file_id': fileId},
            ),
          ];
          break;
        case FileNotificationType.updated:
          title = 'File Updated';
          body = '$senderName updated the file: "$fileName"';
          actions = [
            NotificationAction(
              id: 'view_changes',
              type: NotificationActionType.openItem,
              label: 'View Changes',
              data: {'file_id': fileId},
              isPrimary: true,
            ),
          ];
          break;
        case FileNotificationType.commented:
          title = 'File Comment';
          body = '$senderName commented on file: "$fileName"';
          actions = [
            NotificationAction(
              id: 'view_comment',
              type: NotificationActionType.openItem,
              label: 'View Comment',
              data: {'file_id': fileId},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'reply',
              type: NotificationActionType.respond,
              label: 'Reply',
              data: {'file_id': fileId, 'action': 'reply'},
            ),
          ];
          break;
      }

      final notification = NotificationModel(
        id: '', // Will be generated by API
        title: title,
        body: body,
        category: NotificationCategory.file,
        priority: priority,
        actions: actions,
        metadata: NotificationMetadata(
          entityId: fileId,
          entityType: 'file',
          workspaceId: workspaceId ?? await AppConfig.getCurrentWorkspaceId(),
          projectId: projectId,
          additionalData: additionalData,
        ),
        createdAt: DateTime.now(),
        senderId: await AppConfig.getCurrentUserId(),
        senderName: senderName,
        senderAvatar: senderAvatar,
      );

      // TODO: Re-implement when backend notification API is ready
      // await _notificationService.apiService.createNotification(notification);
    } catch (e) {
    }
  }

  // Workspace notifications
  Future<void> sendWorkspaceNotification({
    required String workspaceId,
    required String workspaceName,
    required String recipientUserId,
    required String senderName,
    String? senderAvatar,
    required WorkspaceNotificationType type,
    Map<String, dynamic>? additionalData,
  }) async {
    try {
      String title = '';
      String body = '';
      NotificationPriority priority = NotificationPriority.medium;
      List<NotificationAction> actions = [];

      switch (type) {
        case WorkspaceNotificationType.invited:
          title = 'Workspace Invitation';
          body = '$senderName invited you to join the workspace "$workspaceName"';
          priority = NotificationPriority.high;
          actions = [
            NotificationAction(
              id: 'accept',
              type: NotificationActionType.approve,
              label: 'Accept',
              data: {'workspace_id': workspaceId, 'action': 'accept'},
              isPrimary: true,
            ),
            NotificationAction(
              id: 'decline',
              type: NotificationActionType.reject,
              label: 'Decline',
              data: {'workspace_id': workspaceId, 'action': 'decline'},
            ),
          ];
          break;
        case WorkspaceNotificationType.roleChanged:
          title = 'Role Changed';
          body = 'Your role in workspace "$workspaceName" has been updated';
          actions = [
            NotificationAction(
              id: 'view_workspace',
              type: NotificationActionType.openItem,
              label: 'View Workspace',
              data: {'workspace_id': workspaceId},
              isPrimary: true,
            ),
          ];
          break;
        case WorkspaceNotificationType.announcement:
          title = 'Workspace Announcement';
          body = 'New announcement in "$workspaceName"';
          actions = [
            NotificationAction(
              id: 'view_announcement',
              type: NotificationActionType.openItem,
              label: 'View Announcement',
              data: {'workspace_id': workspaceId},
              isPrimary: true,
            ),
          ];
          break;
      }

      final notification = NotificationModel(
        id: '', // Will be generated by API
        title: title,
        body: body,
        category: NotificationCategory.workspace,
        priority: priority,
        actions: actions,
        metadata: NotificationMetadata(
          entityId: workspaceId,
          entityType: 'workspace',
          workspaceId: workspaceId,
          additionalData: additionalData,
        ),
        createdAt: DateTime.now(),
        senderId: await AppConfig.getCurrentUserId(),
        senderName: senderName,
        senderAvatar: senderAvatar,
      );

      // TODO: Re-implement when backend notification API is ready
      // await _notificationService.apiService.createNotification(notification);
    } catch (e) {
    }
  }

  // System notifications
  Future<void> sendSystemNotification({
    required String title,
    required String body,
    required String recipientUserId,
    NotificationPriority priority = NotificationPriority.medium,
    List<NotificationAction>? actions,
    String? workspaceId,
    Map<String, dynamic>? additionalData,
  }) async {
    try {
      final notification = NotificationModel(
        id: '', // Will be generated by API
        title: title,
        body: body,
        category: NotificationCategory.system,
        priority: priority,
        actions: actions ?? [],
        metadata: NotificationMetadata(
          entityType: 'system',
          workspaceId: workspaceId ?? await AppConfig.getCurrentWorkspaceId(),
          additionalData: additionalData,
        ),
        createdAt: DateTime.now(),
        senderId: 'system',
        senderName: 'System',
      );

      // TODO: Re-implement when backend notification API is ready
      // await _notificationService.apiService.createNotification(notification);
    } catch (e) {
    }
  }
}

// Enum types for different notification contexts
enum TaskNotificationType {
  assigned,
  completed,
  dueSoon,
  overdue,
  updated,
  commented,
}

enum ProjectNotificationType {
  invited,
  updated,
  completed,
  deadline,
}

enum CalendarNotificationType {
  invited,
  reminder,
  updated,
  cancelled,
}

enum ChatNotificationType {
  message,
  mention,
  channelInvite,
}

enum FileNotificationType {
  shared,
  updated,
  commented,
}

enum WorkspaceNotificationType {
  invited,
  roleChanged,
  announcement,
}